[project]
python = "^3.8"
name = "electronic-prescription-service-api"

[tool.poetry]
name = "electronic-prescription-service-api"
version = "0.0.1-alpha"
description = "Electronic Prescription Service API Definitions"
license = "MIT"
authors = [
    "EPS Team <eps@team.team>"
]
readme = "README.md"
repository = "https://github.com/NHSDigital/electronic-prescription-service-api"
package-mode = false

[tool.poetry.dependencies]
python = "^3.8"
pyyaml = "^6.0"
docopt = "^0.6.2"
jsonpath-rw = "^1.4.0"
semver = "^3.0.4"
gitpython = "^3.1.44"
pytest = "^8.3.4"
requests = "^2.32.3"
boto3 = "^1.37.3"
argparse = "^1.4.0"
pre-commit = "^3.5.0"

[tool.poetry.dev-dependencies]
flake8 = "^5.0.4"
black = "^24.8"
pip-licenses = "^4.5.1"
jinja2 = "^3.1.6"

[tool.poetry.scripts]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
